project:
  type: book

book:
  title: "Using Quarto and RStudio to build Data fellowship module materials"
  subtitle: "MACEPA Data Fellowship - Training Materials"
  chapters:
    - index.qmd
    - building-from-scratch.qmd
    - building-from-existing.qmd

format:
  html:
    theme:
    - cosmo
    - custom.scss
    template-partials: title-block.html
    css: include/webex.css
    include-after-body: include/webex.js
    embed-resources: true 
  pdf:
    documentclass: scrreprt
editor: visual
